linters-settings:
  gocyclo:
    min-complexity: 16
  goconst:
    min-len: 3
    min-occurrences: 5
  lll:
    line-length: 120
linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - nakedret
    - gochecknoglobals
    - errcheck
    - lll
    - gochecknoinits
    - dupl
    - funlen
  fast: false

issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "cyclomatic complexity .* of func `Test.*` is high"
    - "cyclomatic complexity .* of func `readSetting` is high"
