linters-settings:
  gocyclo:
    min-complexity: 19
  goconst:
    min-len: 3
    min-occurrences: 5
  lll:
    line-length: 120
linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - nakedret
    - gochecknoglobals
    - errcheck
    - lll
    - gochecknoinits
    - dupl
    - funlen
    - wsl
    - exhaustive
    - gofumpt
    - nlreturn
    - exhaustivestruct
    - exhaustruct
    - errorlint
    - paralleltest
    - godot
    - forbidigo
    - ifshort
    - cyclop
    - promlinter
    - varnamelen
    - nonamedreturns
    - tagliatelle
    - forcetypeassert
  fast: false

issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "cyclomatic complexity .* of func `Test.*` is high"
    - "cyclomatic complexity .* of func `.*readSetting` is high"
    - "Function name: readSetting, Cyclomatic Complexity"
    - "cognitive complexity .* of func `Test.*"
    - 'Magic number: 0.01\D '
    - 'Magic number: 1\D '
    - 'Magic number: 2\D '
    - 'Magic number: 3\D '
    - 'Magic number: 10\D '
    - 'Magic number: 30\D '
    - 'Magic number: 16\D '
    - 'Magic number: 64\D '
    - 'Magic number: 100\D '
    - 'Magic number: 1024\D '
    - 'Magic number: 1e9\D '
    - 'Magic number: 0644\D '
    - 'Magic number: 0755\D '
    - 'Magic number: 0664\D '
    - 'Magic number: 65536\D '
    - 'Top level comment should end in a period'
    - 'package should be `modgearman_test` instead of `modgearman`'
    - 'Expect WriteFile permissions to be 0600 or less'
    - 'err113:'
    - 'G204: Subprocess launched'
    - 'G114: Use of net/http serve function that has no support for setting timeouts'
    - 'RLIMIT_NOFILE contains underscore'
    - 'O_APPEND contains underscore'
    - 'O_WRONLY contains underscore'
    - 'O_CREATE contains underscore'
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
