linters-settings:
  gocyclo:
    min-complexity: 17
  goconst:
    min-len: 3
    min-occurrences: 5
  lll:
    line-length: 120
linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - nakedret
    - gochecknoglobals
    - errcheck
    - lll
    - gochecknoinits
    - dupl
    - funlen
    - wsl
  fast: false

issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "cyclomatic complexity .* of func `Test.*` is high"
    - "cyclomatic complexity .* of func `readSetting` is high"
    - "cognitive complexity .* of func `Test.*"
    - 'Magic number: 0.01\D '
    - 'Magic number: 1\D '
    - 'Magic number: 10\D '
    - 'Magic number: 16\D '
    - 'Magic number: 100\D '
    - 'Magic number: 1024\D '
    - 'Magic number: 1e9\D '
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
