language: go

go:
  - "1.x"
  - "1.9"
  - "1.10"
  - "1.11"

addons:
  apt:
    packages:
    - gearman-job-server

script:
  -  make citest

after_success:
  - bash <(curl -s https://codecov.io/bash)
